libraryapp/urls.py
from django.conf.urls import url
from django.conf.urls import url, include
from django.urls import path
from .views import *

app_name = "libraryapp"

urlpatterns = [
    url(r'^home$', book_list, name='home'),
    url(r'^books$', book_list, name='books'),
    path('books/<int:book_id>/', book_details, name='book'),
    url(r'^librarians$', list_librarians, name='librarians'),
    url(r'^libraries$', list_libraries, name='libraries'),
    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'^logout/$', logout_user, name='logout'),
    url(r'^book/form$', book_form, name='book_form'),
    url(r'^library/form$', library_form, name='library_form'),
    path('libraries/<int:library_id>/', library_details, name='library'),
    path('librarians/<int:librarian_id>/', librarian_details, name='librarian'),
    path(r'^books/(?P<book_id>[0-9]+)/form$', book_edit_form, name='book_edit_form'),
]

libraryproject/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from libraryapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('libraryapp.urls')),
]

libraryapp/models/book.py
from django.db import models
from .library import Library
from .librarian import Librarian

class Book(models.Model):

    bookTitle = models.CharField(max_length = 100)
    ISBNNumber = models.CharField(max_length = 100)
    Author = models.CharField(max_length = 100)
    YearPublished  = models.IntegerField(max_length = 100)
    location = models.ForeignKey(Library, on_delete = models.CASCADE)
    librarian = models.ForeignKey(Librarian, on_delete=models.CASCADE)

libraryapp/models/librarian.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from .library import Library


class Librarian(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.ForeignKey(
        Library, related_name="librarians",
        null=True, # Makes column nullable in DB
        blank=True, # Allows blank value on objects
        on_delete=models.CASCADE)


# These receiver hooks allow you to continue to
# work with the `User` class in your Python code.


# Every time a `User` is created, a matching `Librarian`
# object will be created and attached as a one-to-one
# property
@receiver(post_save, sender=User)
def create_librarian(sender, instance, created, **kwargs):
    if created:
        Librarian.objects.create(user=instance)

# Every time a `User` is saved, its matching `Librarian`
# object will be saved.
@receiver(post_save, sender=User)
def save_librarian(sender, instance, **kwargs):
    instance.librarian.save()

libraryapp/models/library.py
from django.db import models

class Library(models.Model):

    title = models.CharField(max_length = 100)
    address = models.CharField(max_length = 100)

libraryapp/models/modelfactory.py
import sqlite3

def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

libraryapp/views.py
from django.shortcuts import render

# Create your views here.

libraryapp/views/connection.py
class Connection:
    db_path = "/Users/marywest/workspace/python/libraryproject/db.sqlite3"

libraryapp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

libraryapp/templates/books/detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Books</title>
  </head>
  <body>
<section id="book-details">
    <h1>{{ book.bookTitle }}</h1>
    <h2>By {{ book.Author }}</h2>

    <div>Published in {{ book.YearPublished }}</div>
    <div>ISBN: {{ book.ISBNNumber }}</div>
    <div>Located in the {{ book.location.title }}</div>
    <div>Registered by {{ book.librarian.first_name }} {{ book.librarian.last_name }}</div>
</section>
<form action="{% url 'libraryapp:book' book.id %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="actual_method" value="DELETE">
    <button>Delete</button>
</form>
  <form action="{% url 'libraryapp:book_edit_form' book.id %}" method="GET">
      {% csrf_token %}
      <button>Edit</button>
  </form>
  </body>
</html>

libraryapp/templates/books/form.html
{% extends 'shared/base.html' %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Library</title>
</head>
{% block content %}
<body>
    <h1>Inventory Book</h1>
  <a href="{% url 'libraryapp:book_form' %}">Add Book to Inventory</a>

    {% if book.id is not None %}
        <form action="{% url 'libraryapp:book' book.id %}" method="post">
    {% else %}
        <form action="{% url 'libraryapp:books' %}" method="post">
    {% endif %}
        {% csrf_token %}
        <fieldset>
            <label for="bookTitle">Title: </label>
            <input id="bookTitle" type="text" name="bookTitle" value="{{ book.bookTitle }}">
        </fieldset>
        <fieldset>
            <label for="Author">Author: </label>
            <input id="Author" type="text" name="Author" value="{{ book.Author }}">
        </fieldset>
        <fieldset>
            <label for="YearPublished">Year of publication: </label>
            <input id="YearPublished" type="number" name="YearPublished" value="{{ book.YearPublished }}">
        </fieldset>
        <fieldset>
            <label for="ISBNNumber">ISBN: </label>
            <input id="ISBNNumber" type="text" name="ISBNNumber" value="{{ book.ISBNNumber }}">
        </fieldset>
        <fieldset>
            <label for="location">Library: </label>
            <select id="location" type="text" name="location">
                {% for library in all_libraries %}
                <option {% if library.id == book.location_id %}selected{% endif %} value="{{ library.id }}">
                    {{ library.title }}</option>
                {% endfor %}
            </select>
        </fieldset>

        {% if book.id is not None %}
            <input type="hidden" name="actual_method" value="PUT">
            <input type="submit" value="Update" />
        {% else %}
            <input type="submit" value="Create" />
        {% endif %}

    </form>
</body>
{% endblock %}
</html>

libraryapp/templates/books/list.html
{% extends 'shared/base.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/books.css' %}" />
{% endblock %}

{% block content %}
    <h1>Books</h1>

    <dialog class="infoDialog">
        <div class="infoDialog__message"></div>
        <button class="closeDialog">Close</button>
    </dialog>

    <a href="{% url 'libraryapp:book_form' %}">Add Book to Inventory</a>

    <ol class="books">
    {% for book in all_books %}
        <li class="book">
            <a class="book__title" href="{% url 'libraryapp:book' book.id %}"> {{ book.bookTitle }}</a>
            <div class="book__description">
                by {{book.Author}} published in {{book.YearPublished}}
            </div>
                <button id="detail--{{ book.id }}">Details</button>
        </li>
    {% endfor %}
    </ol>
{% endblock %}

{% block scripts %}
    <script src="{% static 'scripts/books.js' %}"></script>
{% endblock %}

libraryapp/templates/home.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Nashville Library Management System</title>
</head>

<body>

    <h1>Welcome to the Nashville Library Management System</h1>

</body>

</html>

libraryapp/templates/librarians/detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Librarians</title>
  </head>
  <body>
    <h1>{{ librarian.first_name }}</h1>
    <h2> {{ librarian.last_name }}</h2>
  </body>
</html>

libraryapp/templates/librarians/list.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>Librarians</h1>

    <ol>
    {% for librarian in all_librarians %}

    <a href="{% url 'libraryapp:librarian' librarian.id %}"> {{ librarian.first_name }} </a>
    by {{librarian.last_name}}
    {% endfor %}
    </ol>
  </body>
</html>

libraryapp/templates/libraries/detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>{{ library.title }}</h1>
    <h2>{{ library.address }}</h2>
  </body>
</html>

libraryapp/templates/libraries/form.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bangazon</title>
  </head>
  <body>
    <h1>Add Library</h1>


    <form action="{% url 'libraryapp:libraries' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="title">Title: </label>
          <input id="title" type="text" name="title">
      </fieldset>
      <fieldset>
          <label for="address">Address: </label>
          <input id="address" type="text" name="address">
      </fieldset>
      <input type="submit" value="Add It" />
    </form>
  </body>
</html>

libraryapp/templates/libraries/list.html
{% extends 'shared/base.html' %}

{% block content %}
    <h1>Libraries</h1>

    <a href="{% url 'libraryapp:library_form' %}">Add Library</a>

    <ol>
    {% for library in libraries %}
        <li>
            <a href="{% url 'libraryapp:library' library.id %}">
                {{ library.title }}
            </a>
            ({{ library.address }})
            <ul>
            {% for book in library.books %}
                <li>{{ book.bookTitle }}</li>
            {% endfor %}
            </ul>
        </li>
    {% endfor %}
    </ol>
{% endblock %}

libraryapp/templates/library/list.html
{% extends 'shared/base.html' %}

{% block content %}
    <h1>Libraries</h1>

    <a href="{% url 'libraryapp:library_form' %}">Add Library</a>

    <ol>
    {% for library in libraries %}
        <li>
            <a href="{% url 'libraryapp:libraries' library.id %}">
                {{ library.title }}
            </a>
            ({{ library.address }})
            <ul>
            {% for book in library.books %}
                <li>{{ book.bookTitle }}</li>
            {% endfor %}
            </ul>
        </li>
    {% endfor %}
    </ol>
{% endblock %}

libraryapp/templates/shared/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Library</title>

    <link rel="stylesheet" href="{% static 'styles/base.css' %}" />

    {% block css %}
    {% endblock %}
</head>

<body>

    <nav id="site-nav">
        <ol class="navList">
            <li class="navList__route"><a href="{% url 'libraryapp:home' %}">Home</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:libraries' %}">Libraries</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:books' %}">Books</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:librarians' %}">Librarians</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:logout' %}">Logout</a></li>
        </ol>
    </nav>

    <main class="main-content">
        {% block content %}
        {% endblock %}
    </main>

    {% block scripts %}
    {% endblock scripts %}
</body>

</html>